"""initial_geovault_schema

Revision ID: 014c3e7f3ccc
Revises: 
Create Date: 2026-09-11 10:41:17.792010+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '014c3e7f3ccc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captive_commercial_production',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('end_use', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('quantity_mt', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captive_commercial_production_company'), 'captive_commercial_production', ['company'], unique=False)
    op.create_index(op.f('ix_captive_commercial_production_end_use'), 'captive_commercial_production', ['end_use'], unique=False)
    op.create_index(op.f('ix_captive_commercial_production_state'), 'captive_commercial_production', ['state'], unique=False)
    op.create_table('macro_statistical_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.String(length=50), nullable=False),
    sa.Column('table_title', sa.Text(), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_statistical_tables_chapter'), 'macro_statistical_tables', ['chapter'], unique=False)
    op.create_index(op.f('ix_macro_statistical_tables_table_id'), 'macro_statistical_tables', ['table_id'], unique=False)
    op.create_index('ix_macro_tables_file_tab', 'macro_statistical_tables', ['source_file', 'table_id'], unique=False)
    op.create_table('national_annual_production',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_range', sa.String(length=20), nullable=False),
    sa.Column('coking_coal_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('non_coking_coal_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('growth_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_mt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_range')
    )
    op.create_table('parliamentary_benchmarks',
    sa.Column('question_id', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('reference_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('subsidiaries',
    sa.Column('subsidiary_id', sa.String(length=50), nullable=False),
    sa.Column('subsidiary_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('subsidiary_id'),
    sa.UniqueConstraint('subsidiary_name')
    )
    op.create_table('mines',
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('mine_name', sa.String(length=200), nullable=False),
    sa.Column('subsidiary_id', sa.String(length=50), nullable=False),
    sa.Column('mine_type', sa.String(length=50), nullable=False),
    sa.Column('coal_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.subsidiary_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('mine_code')
    )
    op.create_table('coal_quality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ash_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('moisture_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quality_action', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mine_code', 'year', name='uq_coal_quality_mine_year')
    )
    op.create_table('conflicts',
    sa.Column('conflict_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('metric_or_topic', sa.String(length=150), nullable=False),
    sa.Column('source_a_type', sa.String(length=100), nullable=False),
    sa.Column('source_a_reference', sa.String(length=255), nullable=False),
    sa.Column('source_a_value', sa.Text(), nullable=False),
    sa.Column('source_b_type', sa.String(length=100), nullable=False),
    sa.Column('source_b_reference', sa.String(length=255), nullable=False),
    sa.Column('source_b_value', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_policy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    op.create_index(op.f('ix_conflicts_mine_code'), 'conflicts', ['mine_code'], unique=False)
    op.create_index(op.f('ix_conflicts_year'), 'conflicts', ['year'], unique=False)
    op.create_table('dispatch_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dispatch_mt', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('production_dispatch_gap_mt', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('logistics_status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mine_code', 'year', name='uq_dispatch_summary_mine_year')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=True),
    sa.Column('subsidiary_id', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.subsidiary_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_classification'), 'documents', ['classification'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_index(op.f('ix_documents_mine_code'), 'documents', ['mine_code'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_table('geological_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=False),
    sa.Column('depth_or_horizon_m', sa.String(length=100), nullable=False),
    sa.Column('thickness_m', sa.String(length=100), nullable=False),
    sa.Column('structure', sa.String(length=100), nullable=False),
    sa.Column('geological_risk', sa.String(length=50), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mine_code', 'unit', name='uq_geological_unit_mine_unit')
    )
    op.create_table('inspection_register',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('inspection_focus', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('responsible_officer', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_register_mine_code'), 'inspection_register', ['mine_code'], unique=False)
    op.create_index(op.f('ix_inspection_register_year'), 'inspection_register', ['year'], unique=False)
    op.create_table('mining_issue_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('issue_category', sa.String(length=100), nullable=False),
    sa.Column('observed_issue', sa.Text(), nullable=False),
    sa.Column('operational_impact', sa.Text(), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mining_issue_log_mine_code'), 'mining_issue_log', ['mine_code'], unique=False)
    op.create_index(op.f('ix_mining_issue_log_year'), 'mining_issue_log', ['year'], unique=False)
    op.create_table('production_annual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('target_mt', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('actual_production_mt', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('variance_mt', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('achievement_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dispatch_mt', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('equipment_or_face_availability_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mine_code', 'year', name='uq_production_annual_mine_year')
    )
    op.create_index('ix_production_annual_year', 'production_annual', ['year'], unique=False)
    op.create_table('production_monthly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('production_mt', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('monthly_target_mt', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('variance_mt', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mine_code', 'year', 'month', name='uq_production_monthly_mine_ym')
    )
    op.create_index('ix_production_monthly_ym', 'production_monthly', ['year', 'month'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('clearance_level', sa.String(length=50), nullable=False),
    sa.Column('assigned_mine_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_mine_code'], ['mines.mine_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=True),
    sa.Column('subsidiary_id', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('access_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_chunks_auth_scope', 'document_chunks', ['mine_code', 'department', 'classification'], unique=False)
    op.create_index(op.f('ix_document_chunks_classification'), 'document_chunks', ['classification'], unique=False)
    op.create_index(op.f('ix_document_chunks_department'), 'document_chunks', ['department'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_mine_code'), 'document_chunks', ['mine_code'], unique=False)
    op.create_table('query_audit_logs',
    sa.Column('log_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('route_selected', sa.String(length=50), nullable=False),
    sa.Column('authorized_scope_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('evidence_status', sa.String(length=50), nullable=False),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_query_audit_logs_user_id'), 'query_audit_logs', ['user_id'], unique=False)
    op.create_table('user_scopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('max_classification', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scopes_user_id'), 'user_scopes', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('query_id', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(length=100), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_mine_code'), 'evidence', ['mine_code'], unique=False)
    op.create_index(op.f('ix_evidence_query_id'), 'evidence', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_query_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_mine_code'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_user_scopes_user_id'), table_name='user_scopes')
    op.drop_table('user_scopes')
    op.drop_index(op.f('ix_query_audit_logs_user_id'), table_name='query_audit_logs')
    op.drop_table('query_audit_logs')
    op.drop_index(op.f('ix_document_chunks_mine_code'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_department'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_classification'), table_name='document_chunks')
    op.drop_index('ix_chunks_auth_scope', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_production_monthly_ym', table_name='production_monthly')
    op.drop_table('production_monthly')
    op.drop_index('ix_production_annual_year', table_name='production_annual')
    op.drop_table('production_annual')
    op.drop_index(op.f('ix_mining_issue_log_year'), table_name='mining_issue_log')
    op.drop_index(op.f('ix_mining_issue_log_mine_code'), table_name='mining_issue_log')
    op.drop_table('mining_issue_log')
    op.drop_index(op.f('ix_inspection_register_year'), table_name='inspection_register')
    op.drop_index(op.f('ix_inspection_register_mine_code'), table_name='inspection_register')
    op.drop_table('inspection_register')
    op.drop_table('geological_units')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_mine_code'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_classification'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('dispatch_summary')
    op.drop_index(op.f('ix_conflicts_year'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_mine_code'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_table('coal_quality')
    op.drop_table('mines')
    op.drop_table('subsidiaries')
    op.drop_table('parliamentary_benchmarks')
    op.drop_table('national_annual_production')
    op.drop_index('ix_macro_tables_file_tab', table_name='macro_statistical_tables')
    op.drop_index(op.f('ix_macro_statistical_tables_table_id'), table_name='macro_statistical_tables')
    op.drop_index(op.f('ix_macro_statistical_tables_chapter'), table_name='macro_statistical_tables')
    op.drop_table('macro_statistical_tables')
    op.drop_index(op.f('ix_captive_commercial_production_state'), table_name='captive_commercial_production')
    op.drop_index(op.f('ix_captive_commercial_production_end_use'), table_name='captive_commercial_production')
    op.drop_index(op.f('ix_captive_commercial_production_company'), table_name='captive_commercial_production')
    op.drop_table('captive_commercial_production')
    # ### end Alembic commands ###
