"""add_geological_and_spatial_schema

Revision ID: c770e91eae3b
Revises: 014c3e7f3ccc
Create Date: 2026-09-21 11:22:17.223719+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c770e91eae3b'
down_revision: Union[str, None] = '014c3e7f3ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_benchmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qa_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_source', sa.String(length=100), nullable=False),
    sa.Column('expected_operation', sa.String(length=50), nullable=False),
    sa.Column('expected_key', sa.String(length=100), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_benchmarks_mine_code'), 'qa_benchmarks', ['mine_code'], unique=False)
    op.create_index(op.f('ix_qa_benchmarks_qa_id'), 'qa_benchmarks', ['qa_id'], unique=True)
    op.create_table('spatial_borehole_intervals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borehole_id', sa.String(length=50), nullable=False),
    sa.Column('interval_no', sa.Integer(), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('from_depth_m', sa.Float(), nullable=False),
    sa.Column('to_depth_m', sa.Float(), nullable=False),
    sa.Column('thickness_m', sa.Float(), nullable=False),
    sa.Column('lithology', sa.String(length=100), nullable=False),
    sa.Column('coal_seam', sa.String(length=100), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_borehole_intervals_geom', 'spatial_borehole_intervals', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_borehole_intervals_borehole_id'), 'spatial_borehole_intervals', ['borehole_id'], unique=False)
    op.create_index(op.f('ix_spatial_borehole_intervals_coal_seam'), 'spatial_borehole_intervals', ['coal_seam'], unique=False)
    op.create_index(op.f('ix_spatial_borehole_intervals_lithology'), 'spatial_borehole_intervals', ['lithology'], unique=False)
    op.create_index(op.f('ix_spatial_borehole_intervals_mine_code'), 'spatial_borehole_intervals', ['mine_code'], unique=False)
    op.create_table('spatial_borehole_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('borehole_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('azimuth_deg', sa.Float(), nullable=True),
    sa.Column('inclination_deg', sa.Float(), nullable=True),
    sa.Column('total_depth_m', sa.Float(), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_borehole_traces_geom', 'spatial_borehole_traces', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_borehole_traces_borehole_id'), 'spatial_borehole_traces', ['borehole_id'], unique=False)
    op.create_index(op.f('ix_spatial_borehole_traces_mine_code'), 'spatial_borehole_traces', ['mine_code'], unique=False)
    op.create_index(op.f('ix_spatial_borehole_traces_trace_id'), 'spatial_borehole_traces', ['trace_id'], unique=False)
    op.create_table('spatial_boreholes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borehole_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('lithology', sa.String(length=100), nullable=True),
    sa.Column('intersected_seam', sa.String(length=100), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_boreholes_geom', 'spatial_boreholes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_boreholes_borehole_id'), 'spatial_boreholes', ['borehole_id'], unique=False)
    op.create_index(op.f('ix_spatial_boreholes_mine_code'), 'spatial_boreholes', ['mine_code'], unique=False)
    op.create_table('spatial_coal_seam_belts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seam_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('feature_type', sa.String(length=100), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_coal_seam_belts_geom', 'spatial_coal_seam_belts', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_coal_seam_belts_mine_code'), 'spatial_coal_seam_belts', ['mine_code'], unique=False)
    op.create_index(op.f('ix_spatial_coal_seam_belts_seam_id'), 'spatial_coal_seam_belts', ['seam_id'], unique=False)
    op.create_table('spatial_geological_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('contact_type', sa.String(length=100), nullable=False),
    sa.Column('unit_a', sa.String(length=100), nullable=True),
    sa.Column('unit_b', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_geological_contacts_geom', 'spatial_geological_contacts', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_geological_contacts_contact_id'), 'spatial_geological_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_spatial_geological_contacts_mine_code'), 'spatial_geological_contacts', ['mine_code'], unique=False)
    op.create_table('spatial_geological_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_geological_events_geom', 'spatial_geological_events', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_geological_events_event_id'), 'spatial_geological_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_spatial_geological_events_mine_code'), 'spatial_geological_events', ['mine_code'], unique=False)
    op.create_table('spatial_geological_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geology_unit_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('age', sa.String(length=100), nullable=True),
    sa.Column('relative_order', sa.Integer(), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_geological_units_geom', 'spatial_geological_units', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_geological_units_geology_unit_id'), 'spatial_geological_units', ['geology_unit_id'], unique=False)
    op.create_index(op.f('ix_spatial_geological_units_mine_code'), 'spatial_geological_units', ['mine_code'], unique=False)
    op.create_table('spatial_geotechnical_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('zone_type', sa.String(length=100), nullable=False),
    sa.Column('risk_class', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_geotechnical_zones_geom', 'spatial_geotechnical_zones', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_geotechnical_zones_mine_code'), 'spatial_geotechnical_zones', ['mine_code'], unique=False)
    op.create_index(op.f('ix_spatial_geotechnical_zones_zone_id'), 'spatial_geotechnical_zones', ['zone_id'], unique=False)
    op.create_table('spatial_landuse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landuse_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('landuse_class', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_landuse_geom', 'spatial_landuse', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_landuse_landuse_id'), 'spatial_landuse', ['landuse_id'], unique=False)
    op.create_index(op.f('ix_spatial_landuse_mine_code'), 'spatial_landuse', ['mine_code'], unique=False)
    op.create_table('spatial_survey_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_point_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('point_type', sa.String(length=50), nullable=False),
    sa.Column('rl_m', sa.Float(), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False, nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_survey_points_geom', 'spatial_survey_points', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_spatial_survey_points_mine_code'), 'spatial_survey_points', ['mine_code'], unique=False)
    op.create_index(op.f('ix_spatial_survey_points_survey_point_id'), 'spatial_survey_points', ['survey_point_id'], unique=False)
    op.create_table('boreholes_master',
    sa.Column('borehole_id', sa.String(length=50), nullable=False),
    sa.Column('mine_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('mine_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rl_m', sa.Float(), nullable=False),
    sa.Column('total_depth_m', sa.Float(), nullable=False),
    sa.Column('intersected_seam', sa.String(length=100), nullable=True),
    sa.Column('from_depth_m', sa.Float(), nullable=True),
    sa.Column('to_depth_m', sa.Float(), nullable=True),
    sa.Column('lithology_summary', sa.Text(), nullable=True),
    sa.Column('coal_thickness_m', sa.Float(), nullable=True),
    sa.Column('quality_band', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('borehole_id')
    )
    op.create_index(op.f('ix_boreholes_master_mine_code'), 'boreholes_master', ['mine_code'], unique=False)
    op.create_index(op.f('ix_boreholes_master_mine_id'), 'boreholes_master', ['mine_id'], unique=False)
    op.create_table('coal_seams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seam_id', sa.String(length=100), nullable=False),
    sa.Column('mine_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('mine_name', sa.String(length=200), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('avg_thickness_m', sa.Float(), nullable=False),
    sa.Column('synthetic_dip_deg', sa.Float(), nullable=True),
    sa.Column('synthetic_strike_deg', sa.Float(), nullable=True),
    sa.Column('continuity', sa.String(length=100), nullable=True),
    sa.Column('quality_band', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coal_seams_mine_code'), 'coal_seams', ['mine_code'], unique=False)
    op.create_index(op.f('ix_coal_seams_seam_id'), 'coal_seams', ['seam_id'], unique=False)
    op.create_table('cross_section_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('chainage_m', sa.Float(), nullable=False),
    sa.Column('ground_rl_m', sa.Float(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_section_points_mine_code'), 'cross_section_points', ['mine_code'], unique=False)
    op.create_index(op.f('ix_cross_section_points_section_id'), 'cross_section_points', ['section_id'], unique=False)
    op.create_table('environmental_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('pm10_ug_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pm25_ug_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('water_treated_ml', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('reclamation_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('plantation_trees_count', sa.Integer(), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_records_financial_year'), 'environmental_records', ['financial_year'], unique=False)
    op.create_index(op.f('ix_environmental_records_mine_code'), 'environmental_records', ['mine_code'], unique=False)
    op.create_index(op.f('ix_environmental_records_record_id'), 'environmental_records', ['record_id'], unique=False)
    op.create_table('equipment_fleet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('operating_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('downtime_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('financial_year', sa.String(length=20), nullable=True),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_fleet_equipment_id'), 'equipment_fleet', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_fleet_financial_year'), 'equipment_fleet', ['financial_year'], unique=False)
    op.create_index(op.f('ix_equipment_fleet_mine_code'), 'equipment_fleet', ['mine_code'], unique=False)
    op.create_index('ix_equipment_fleet_mine_type', 'equipment_fleet', ['mine_code', 'equipment_type'], unique=False)
    op.create_table('geological_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('mine_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geological_events_event_id'), 'geological_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_geological_events_financial_year'), 'geological_events', ['financial_year'], unique=False)
    op.create_index(op.f('ix_geological_events_mine_code'), 'geological_events', ['mine_code'], unique=False)
    op.create_table('geotechnical_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.String(length=100), nullable=False),
    sa.Column('mine_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('zone_type', sa.String(length=100), nullable=False),
    sa.Column('risk_class', sa.String(length=50), nullable=False),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geotechnical_zones_mine_code'), 'geotechnical_zones', ['mine_code'], unique=False)
    op.create_index(op.f('ix_geotechnical_zones_zone_id'), 'geotechnical_zones', ['zone_id'], unique=False)
    op.create_table('safety_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('cause_category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('dgms_reportable', sa.Boolean(), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_records_financial_year'), 'safety_records', ['financial_year'], unique=False)
    op.create_index(op.f('ix_safety_records_incident_id'), 'safety_records', ['incident_id'], unique=False)
    op.create_index(op.f('ix_safety_records_mine_code'), 'safety_records', ['mine_code'], unique=False)
    op.create_table('survey_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_point_id', sa.String(length=100), nullable=False),
    sa.Column('mine_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rl_m', sa.Float(), nullable=False),
    sa.Column('point_type', sa.String(length=50), nullable=False),
    sa.Column('survey_date', sa.String(length=50), nullable=True),
    sa.Column('horizontal_accuracy_m', sa.Float(), nullable=True),
    sa.Column('vertical_accuracy_m', sa.Float(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_points_mine_code'), 'survey_points', ['mine_code'], unique=False)
    op.create_index(op.f('ix_survey_points_survey_point_id'), 'survey_points', ['survey_point_id'], unique=False)
    op.create_table('borehole_intervals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borehole_id', sa.String(length=50), nullable=False),
    sa.Column('mine_id', sa.String(length=50), nullable=False),
    sa.Column('mine_code', sa.String(length=20), nullable=False),
    sa.Column('interval_no', sa.Integer(), nullable=False),
    sa.Column('from_depth_m', sa.Float(), nullable=False),
    sa.Column('to_depth_m', sa.Float(), nullable=False),
    sa.Column('thickness_m', sa.Float(), nullable=False),
    sa.Column('lithology', sa.String(length=100), nullable=False),
    sa.Column('stratigraphic_unit', sa.String(length=100), nullable=True),
    sa.Column('coal_bearing', sa.String(length=20), nullable=True),
    sa.Column('coal_seam', sa.String(length=100), nullable=True),
    sa.Column('weathering_class', sa.String(length=50), nullable=True),
    sa.Column('sample_id', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('provenance_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borehole_id'], ['boreholes_master.borehole_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mine_code'], ['mines.mine_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_borehole_intervals_bh_interval', 'borehole_intervals', ['borehole_id', 'interval_no'], unique=False)
    op.create_index(op.f('ix_borehole_intervals_borehole_id'), 'borehole_intervals', ['borehole_id'], unique=False)
    op.create_index(op.f('ix_borehole_intervals_coal_seam'), 'borehole_intervals', ['coal_seam'], unique=False)
    op.create_index(op.f('ix_borehole_intervals_lithology'), 'borehole_intervals', ['lithology'], unique=False)
    op.create_index(op.f('ix_borehole_intervals_mine_code'), 'borehole_intervals', ['mine_code'], unique=False)
    op.add_column('document_chunks', sa.Column('financial_year', sa.String(length=50), nullable=True))
    op.add_column('document_chunks', sa.Column('provenance_type', sa.String(length=50), server_default='HISTORICAL_COAL_DATA', nullable=False))
    op.create_index(op.f('ix_document_chunks_financial_year'), 'document_chunks', ['financial_year'], unique=False)
    op.add_column('documents', sa.Column('financial_year', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('report_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('provenance_type', sa.String(length=50), server_default='HISTORICAL_COAL_DATA', nullable=False))
    op.create_index(op.f('ix_documents_financial_year'), 'documents', ['financial_year'], unique=False)
    op.add_column('mines', sa.Column('mine_id', sa.String(length=50), nullable=True))
    op.add_column('mines', sa.Column('geospatial_mine_id', sa.String(length=50), nullable=True))
    op.add_column('mines', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('mines', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('mines', sa.Column('coalfield', sa.String(length=100), nullable=True))
    op.add_column('mines', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('mines', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('mines', sa.Column('provenance_type', sa.String(length=50), server_default='HISTORICAL_COAL_DATA', nullable=False))
    op.alter_column('mines', 'coal_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('mines', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_mines_mine_id'), 'mines', ['mine_id'], unique=True)
    op.add_column('production_annual', sa.Column('financial_year', sa.String(length=20), nullable=True))
    op.add_column('production_annual', sa.Column('yoy_growth_pct', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('production_annual', sa.Column('target_ob_mcu_m', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('production_annual', sa.Column('actual_ob_mcu_m', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('production_annual', sa.Column('stripping_ratio_target', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('production_annual', sa.Column('stripping_ratio_actual', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('production_annual', sa.Column('manpower_available', sa.Integer(), nullable=True))
    op.add_column('production_annual', sa.Column('hemm_availability_pct', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('production_annual', sa.Column('downtime_hours', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('production_annual', sa.Column('rainfall_impact_days', sa.Integer(), nullable=True))
    op.add_column('production_annual', sa.Column('safety_incident_count', sa.Integer(), nullable=True))
    op.add_column('production_annual', sa.Column('ltifr', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('production_annual', sa.Column('fatalities', sa.Integer(), nullable=True))
    op.add_column('production_annual', sa.Column('reclamation_ha', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('production_annual', sa.Column('mine_water_treated_ml', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('production_annual', sa.Column('dust_compliance_pct', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('production_annual', sa.Column('primary_cause_of_shortfall', sa.Text(), nullable=True))
    op.add_column('production_annual', sa.Column('geological_observation', sa.Text(), nullable=True))
    op.add_column('production_annual', sa.Column('provenance_type', sa.String(length=50), server_default='HISTORICAL_COAL_DATA', nullable=False))
    op.create_index(op.f('ix_production_annual_financial_year'), 'production_annual', ['financial_year'], unique=False)
    op.create_index('ix_production_annual_mine_fy', 'production_annual', ['mine_code', 'financial_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_production_annual_mine_fy', table_name='production_annual')
    op.drop_index(op.f('ix_production_annual_financial_year'), table_name='production_annual')
    op.drop_column('production_annual', 'provenance_type')
    op.drop_column('production_annual', 'geological_observation')
    op.drop_column('production_annual', 'primary_cause_of_shortfall')
    op.drop_column('production_annual', 'dust_compliance_pct')
    op.drop_column('production_annual', 'mine_water_treated_ml')
    op.drop_column('production_annual', 'reclamation_ha')
    op.drop_column('production_annual', 'fatalities')
    op.drop_column('production_annual', 'ltifr')
    op.drop_column('production_annual', 'safety_incident_count')
    op.drop_column('production_annual', 'rainfall_impact_days')
    op.drop_column('production_annual', 'downtime_hours')
    op.drop_column('production_annual', 'hemm_availability_pct')
    op.drop_column('production_annual', 'manpower_available')
    op.drop_column('production_annual', 'stripping_ratio_actual')
    op.drop_column('production_annual', 'stripping_ratio_target')
    op.drop_column('production_annual', 'actual_ob_mcu_m')
    op.drop_column('production_annual', 'target_ob_mcu_m')
    op.drop_column('production_annual', 'yoy_growth_pct')
    op.drop_column('production_annual', 'financial_year')
    op.drop_index(op.f('ix_mines_mine_id'), table_name='mines')
    op.alter_column('mines', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mines', 'coal_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('mines', 'provenance_type')
    op.drop_column('mines', 'longitude')
    op.drop_column('mines', 'latitude')
    op.drop_column('mines', 'coalfield')
    op.drop_column('mines', 'district')
    op.drop_column('mines', 'state')
    op.drop_column('mines', 'geospatial_mine_id')
    op.drop_column('mines', 'mine_id')
    op.drop_index(op.f('ix_documents_financial_year'), table_name='documents')
    op.drop_column('documents', 'provenance_type')
    op.drop_column('documents', 'report_type')
    op.drop_column('documents', 'financial_year')
    op.drop_index(op.f('ix_document_chunks_financial_year'), table_name='document_chunks')
    op.drop_column('document_chunks', 'provenance_type')
    op.drop_column('document_chunks', 'financial_year')
    op.drop_index(op.f('ix_borehole_intervals_mine_code'), table_name='borehole_intervals')
    op.drop_index(op.f('ix_borehole_intervals_lithology'), table_name='borehole_intervals')
    op.drop_index(op.f('ix_borehole_intervals_coal_seam'), table_name='borehole_intervals')
    op.drop_index(op.f('ix_borehole_intervals_borehole_id'), table_name='borehole_intervals')
    op.drop_index('ix_borehole_intervals_bh_interval', table_name='borehole_intervals')
    op.drop_table('borehole_intervals')
    op.drop_index(op.f('ix_survey_points_survey_point_id'), table_name='survey_points')
    op.drop_index(op.f('ix_survey_points_mine_code'), table_name='survey_points')
    op.drop_table('survey_points')
    op.drop_index(op.f('ix_safety_records_mine_code'), table_name='safety_records')
    op.drop_index(op.f('ix_safety_records_incident_id'), table_name='safety_records')
    op.drop_index(op.f('ix_safety_records_financial_year'), table_name='safety_records')
    op.drop_table('safety_records')
    op.drop_index(op.f('ix_geotechnical_zones_zone_id'), table_name='geotechnical_zones')
    op.drop_index(op.f('ix_geotechnical_zones_mine_code'), table_name='geotechnical_zones')
    op.drop_table('geotechnical_zones')
    op.drop_index(op.f('ix_geological_events_mine_code'), table_name='geological_events')
    op.drop_index(op.f('ix_geological_events_financial_year'), table_name='geological_events')
    op.drop_index(op.f('ix_geological_events_event_id'), table_name='geological_events')
    op.drop_table('geological_events')
    op.drop_index('ix_equipment_fleet_mine_type', table_name='equipment_fleet')
    op.drop_index(op.f('ix_equipment_fleet_mine_code'), table_name='equipment_fleet')
    op.drop_index(op.f('ix_equipment_fleet_financial_year'), table_name='equipment_fleet')
    op.drop_index(op.f('ix_equipment_fleet_equipment_id'), table_name='equipment_fleet')
    op.drop_table('equipment_fleet')
    op.drop_index(op.f('ix_environmental_records_record_id'), table_name='environmental_records')
    op.drop_index(op.f('ix_environmental_records_mine_code'), table_name='environmental_records')
    op.drop_index(op.f('ix_environmental_records_financial_year'), table_name='environmental_records')
    op.drop_table('environmental_records')
    op.drop_index(op.f('ix_cross_section_points_section_id'), table_name='cross_section_points')
    op.drop_index(op.f('ix_cross_section_points_mine_code'), table_name='cross_section_points')
    op.drop_table('cross_section_points')
    op.drop_index(op.f('ix_coal_seams_seam_id'), table_name='coal_seams')
    op.drop_index(op.f('ix_coal_seams_mine_code'), table_name='coal_seams')
    op.drop_table('coal_seams')
    op.drop_index(op.f('ix_boreholes_master_mine_id'), table_name='boreholes_master')
    op.drop_index(op.f('ix_boreholes_master_mine_code'), table_name='boreholes_master')
    op.drop_table('boreholes_master')
    op.drop_index(op.f('ix_spatial_survey_points_survey_point_id'), table_name='spatial_survey_points')
    op.drop_index(op.f('ix_spatial_survey_points_mine_code'), table_name='spatial_survey_points')
    op.drop_index('idx_spatial_survey_points_geom', table_name='spatial_survey_points', postgresql_using='gist')
    op.drop_table('spatial_survey_points')
    op.drop_index(op.f('ix_spatial_landuse_mine_code'), table_name='spatial_landuse')
    op.drop_index(op.f('ix_spatial_landuse_landuse_id'), table_name='spatial_landuse')
    op.drop_index('idx_spatial_landuse_geom', table_name='spatial_landuse', postgresql_using='gist')
    op.drop_table('spatial_landuse')
    op.drop_index(op.f('ix_spatial_geotechnical_zones_zone_id'), table_name='spatial_geotechnical_zones')
    op.drop_index(op.f('ix_spatial_geotechnical_zones_mine_code'), table_name='spatial_geotechnical_zones')
    op.drop_index('idx_spatial_geotechnical_zones_geom', table_name='spatial_geotechnical_zones', postgresql_using='gist')
    op.drop_table('spatial_geotechnical_zones')
    op.drop_index(op.f('ix_spatial_geological_units_mine_code'), table_name='spatial_geological_units')
    op.drop_index(op.f('ix_spatial_geological_units_geology_unit_id'), table_name='spatial_geological_units')
    op.drop_index('idx_spatial_geological_units_geom', table_name='spatial_geological_units', postgresql_using='gist')
    op.drop_table('spatial_geological_units')
    op.drop_index(op.f('ix_spatial_geological_events_mine_code'), table_name='spatial_geological_events')
    op.drop_index(op.f('ix_spatial_geological_events_event_id'), table_name='spatial_geological_events')
    op.drop_index('idx_spatial_geological_events_geom', table_name='spatial_geological_events', postgresql_using='gist')
    op.drop_table('spatial_geological_events')
    op.drop_index(op.f('ix_spatial_geological_contacts_mine_code'), table_name='spatial_geological_contacts')
    op.drop_index(op.f('ix_spatial_geological_contacts_contact_id'), table_name='spatial_geological_contacts')
    op.drop_index('idx_spatial_geological_contacts_geom', table_name='spatial_geological_contacts', postgresql_using='gist')
    op.drop_table('spatial_geological_contacts')
    op.drop_index(op.f('ix_spatial_coal_seam_belts_seam_id'), table_name='spatial_coal_seam_belts')
    op.drop_index(op.f('ix_spatial_coal_seam_belts_mine_code'), table_name='spatial_coal_seam_belts')
    op.drop_index('idx_spatial_coal_seam_belts_geom', table_name='spatial_coal_seam_belts', postgresql_using='gist')
    op.drop_table('spatial_coal_seam_belts')
    op.drop_index(op.f('ix_spatial_boreholes_mine_code'), table_name='spatial_boreholes')
    op.drop_index(op.f('ix_spatial_boreholes_borehole_id'), table_name='spatial_boreholes')
    op.drop_index('idx_spatial_boreholes_geom', table_name='spatial_boreholes', postgresql_using='gist')
    op.drop_table('spatial_boreholes')
    op.drop_index(op.f('ix_spatial_borehole_traces_trace_id'), table_name='spatial_borehole_traces')
    op.drop_index(op.f('ix_spatial_borehole_traces_mine_code'), table_name='spatial_borehole_traces')
    op.drop_index(op.f('ix_spatial_borehole_traces_borehole_id'), table_name='spatial_borehole_traces')
    op.drop_index('idx_spatial_borehole_traces_geom', table_name='spatial_borehole_traces', postgresql_using='gist')
    op.drop_table('spatial_borehole_traces')
    op.drop_index(op.f('ix_spatial_borehole_intervals_mine_code'), table_name='spatial_borehole_intervals')
    op.drop_index(op.f('ix_spatial_borehole_intervals_lithology'), table_name='spatial_borehole_intervals')
    op.drop_index(op.f('ix_spatial_borehole_intervals_coal_seam'), table_name='spatial_borehole_intervals')
    op.drop_index(op.f('ix_spatial_borehole_intervals_borehole_id'), table_name='spatial_borehole_intervals')
    op.drop_index('idx_spatial_borehole_intervals_geom', table_name='spatial_borehole_intervals', postgresql_using='gist')
    op.drop_table('spatial_borehole_intervals')
    op.drop_index(op.f('ix_qa_benchmarks_qa_id'), table_name='qa_benchmarks')
    op.drop_index(op.f('ix_qa_benchmarks_mine_code'), table_name='qa_benchmarks')
    op.drop_table('qa_benchmarks')
    # ### end Alembic commands ###
